name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup C++ environment
      uses: kurocha/setup-cpp@v1
#     - name: Build c++ project
#       uses: nicledomaS/cmake_build_action@v1
#       with:
#         # Git submodule update
#         submodule_update: off# optional, default is OFF
#         # Cmake args (example -D<ARG1>=value;-D<ARG1>=value)
#         # Run unit tests
#         run_tests: off# optional, default is OFF
#         # Cmake arg for turn build unit test (if need)
#         # For multi-configuration tools, choose configuration <Release or Debug>
#         config: Release# optional, default is Release
#     - name: make
#       run: make
#     - name: make check
#       run: make check
#     - name: make distcheck
#       run: make distcheck
